export const EtiquetasGenerales_ES = {
    General: {
        //---------------------ENCABEZADOS------------------------------
        Et_TituloEliminaRegistro: 'Eliminar registro',
        Et_TituloEliminaRegistros: 'Eliminar registros',
        Et_TituloCriterioBusqueda: 'Criterio de búsqueda',
        Et_TituloConfirmaregistro: 'Confirmación',
        Et_TituloDialogoMensaje: 'Mensaje',
        //---------------------Confirmaciones---------------------------
        TextoEliminarRegistro: '¿Desea eliminar el registro? ',
        //---------------------BOTONES----------------------------------
        Et_tbnInsertar: 'Crear',
        Et_tbnEditar: 'Editar',
        Et_tbnVisualizar: 'Visualizar resultados',
        Et_tbnGuardar: 'Guardar',
        Et_tbnAceptar: 'Aceptar',
        Et_tbnCancelar: 'Cancelar',
        Et_tbnEliminar: 'Eliminar',
        Et_tbnPublicar: 'Publicar',
        Et_tbnNoPublicar: 'No Publicar',
        Et_tbnFavorito: 'Favorito',
        Et_tbnPrincipal: 'Principal',
        Et_tbnLimpiar: 'Limpiar',
        Et_tbnSi: 'Sí',
        Et_tbnNo: 'No',
        Et_tbnAtras: 'Atrás',
        Et_tbnSiguiente: 'Siguiente',
        Et_tbnBusqueda: 'Buscar',
        Et_tbnCerrarSesion: 'Cerrar Sesión',
        Et_tbnSubir: 'Subir',
        Et_tbnBajar: 'Bajar',
        Et_tbnCerrar: 'Cerrar',
        Et_tbnEliminarRegistro: "Sí, eliminar el registro",
        Et_tbnMantenerRegistro: "No, mantener el registro",
        Et_tbnAgregar: 'Agregar',
        Et_tbnAgregarC: 'Agregar contenido',
        Et_tbnAgregarE: 'Crear encuesta',
        //---------------------TABLAS-----------------------------------
        Et_tblAcciones: 'Acciones',
        Et_tblDetalles: 'Detalle',
        Et_tblTableEmty: 'Ningún dato disponible',
        Et_tblItems: 'Filas por página: ',
        Et_tblItemsDescription: 'Filas visibles de la {0} a la {1} de un total de {2}.',
        //---------------------TEXTOS--------------------------------
        Et_tblSiTildado: 'Sí',
        Et_lblEs: 'Español',
        Et_lblEn: 'Inglés',
        Et_lblAllElemnts: 'Todas',
        Et_tblNombre: 'Nombre',
        Et_tblCode: 'Código',
        Et_tblDescripcion: 'Descripción',
        Et_tblEstado: 'Activación',
        Et_tblActivo: 'Activo',
        Et_tblInactivo: 'Inactivo',
        Et_Select: 'Seleccione',
        Et_Seleccionar: 'Seleccionar',
        Et_NoAplica: 'No aplica',
        Et_tblCusIde: 'Identificación',
        Et_tblCusOtherIdeShort: 'CIF',
        Et_tblCusOtherIde: 'Número CIF',
        Et_tblObservation: 'Observaciones',
        Et_tblClasificacion: 'Clasificación',
        Et_tblCategoria: 'Categoría',
        Et_tblTipo: 'Tipo',
        Et_tblTipoRequisito: 'Obligatorio',
        Et_tblTipoOpcional: 'Opcional',
        Et_tblBloque: 'Bloque',
        Et_tblRequisitos: 'Requisitos',
        Et_tblFormatoArchivosPermitidos: 'Formatos de archivos',
        Et_Requisito: 'Requisito',
        Et_tblRequisitoConAdjunto: 'El requisito requiere adjuntar archivo.',
        Et_tblAdminFormatoAdjunto: 'Gestionar formatos permitidos',
        Et_tblAdjunto: 'Adjunto',
        Et_tblSinOpciones: 'Sin opciones',
        Et_tblDatosGenerales: 'Datos generales',
        Et_tblPrograma: 'Programa',
        Et_tblProgramas: 'Programas',
        Et_tblTipoPeriodo: 'Tipo de Periodo',
        Et_tblPeriodo: 'Periodo',
        Et_tblAnno: 'Año',
        Et_tblSede: 'Sede',
        Et_tblSedes: 'Sedes',
        Et_tblFechaAprobacion: 'Fecha Aprobación',
        Et_tblEstudiante: 'Estudiante',
        Et_tblAprobacion: 'Aprobación',
        Et_tblArchivo: 'Archivo',
        Et_tblCompania: 'Compañía',
        Et_tblComentarios: 'Comentarios',
        Et_tvlAula: 'Aula',
        Et_tvlAulas: 'Aulas',
        Et_tvlRecursos: 'Recursos',
        Et_tvlEdificio: 'Edificio',
        Et_tvlPiso: 'Piso',
        Et_tvlTipoAula: 'Tipo de Aula',
        Et_tvlCapacidad: 'Capacidad',
        Et_tvlDireccion: 'Dirección',
        Et_tvlAulaDiscapaitados: 'Habilitada para discapacitados',
        Et_tvlCantidad: 'Cantidad',
        Et_tblAprobado: 'Aprobado',
        Et_tblPendiente: 'Pendiente',
        Et_tvlJornada: 'Jornada',
        Et_tvHoraIncio: 'Hora Inicio',
        Et_tvHoraFinal: 'Hora Final',
        Et_tvDiasSemana: 'Días de semana',
        Et_tvLunes: 'Lunes',
        Et_tvMartes: 'Martes',
        Et_tvMiercoles: 'Miércoles',
        Et_tvJueves: 'Jueves',
        Et_tvViernes: 'Viernes',
        Et_tvSabado: 'Sábado',
        Et_tvDomingo: 'Domingo',
        Et_tvListaRecursos: 'Lista de recursos',
        Et_tblInfoRegistrosActivos: '*Solo se mostrarán registros activos.',
        Et_FiltroDscRecursos: 'Descripción del recurso',
        Et_FiltroDscSede: 'Descripción de la sede',
        Et_FiltroDscCursos: 'Descripción del curso',
        Et_FiltroDscFormatos: 'Descripción del formato',
        Et_tblGrupo: 'Grupo',
        Et_tblSubGrupo: 'Subgrupo',
        Et_tblPublicado: 'Publicado',
        Et_tblNoPublicado: 'Sin Publicar',
        Et_tblCupo: 'Cupo',
        Et_tblIniciaT: 'Inicia: ',
        Et_tblFinalizaT: 'Finaliza: ',
        Et_Profesor: 'Profesor',
        Et_Dia: 'Día',
        Et_Horario: 'Horario',
        Et_tblDetalleFechas: 'Detalle de Fechas',
        Et_tblPeriodoAcademico: 'Periodo Académico',
        Et_tblInscripciones: 'Inscripciones',
        Et_tblInicioPeriodo: 'Inicio periodo',
        Et_tblFinPeriodo: 'Fin periodo',
        Et_tblUsuario: 'Usuario',
        Et_tblCliente: 'CIF',
        Et_tblAccion: 'Acción',
        Et_tblFechaDesde: 'Fecha desde',
        Et_tblFechaHasta: 'Fecha hasta',
        Et_tblGeneral: 'General',
        Et_tblIntensidadHoraria: 'Intensidad Horaria',
        Et_ValidaCampoRequerido: 'El campo {0} es requerido.',
    },
    Reportes: {
        Et_TituloPrincipal: 'Reportes',
        Et_LblExportaPdf: 'Pdf',
        Et_LblExportaXls: 'Xls',
        Et_LblExportaDoc: 'Doc'
    },
    Login: {
        Et_btnAcceso: 'Acceso',
        Et_TituloPrincipal: 'Iniciar Sesión Usuario',
        Et_txtUsuario: 'Ingrese su Usuario',
        Et_txtPassword: 'Ingrese su contraseña'
    },
    HomeModulo: {
        Et_Titulo: 'Explore en los diferentes submódulos',
        Et_Parrafo1: 'En el panel de la izquierda podrá encontrar el contenido que está buscando, intente con',
        Et_Parrafo2: 'Favoritos o Menú'
    },
    NotFound: {
        Et_btnAccion: 'Regresar a Inicio'
    },
    IdiomaModal: {
        Et_TituloPrincipal: 'Seleccione su Idioma'
    },
    MenuDerecha: {
        Et_btnSalir: 'Salir',
    },
    MenuIzquierda: {
        Et_LblHeader: 'Módulo Académico',
        Et_LblFavoritos: 'Favoritos',
        Et_LblSubmodulos: 'Menú'
    },
    IdleTimeOutModal: {
        Et_txtFinSesionTitulo: 'Su tiempo de sesión ha expirado.',
        Et_txtFinSeguir: '¿Desea seguir navegando?'
    },
    CargandoModal: {
        Et_Procesando: "Procesando, por favor espere.",
        Et_Cargando: "Cargando, por favor espere."
    },
    ToolbarButtons: {
        Et_BtnEnviar: 'Enviar',
        Et_BtnAjustes: 'Ajustes',
        Et_BtnImprimir: 'Imprimir'
    },
    DialogoSubirImagen: {
        Et_TituloPrincipal: 'Subir Imagen',
        Et_FotoPerfil: 'Foto de perfil',
        Et_BtnSubir: 'Cargar Foto',
        Et_BtnCamara: 'Tomar Foto'
    },
    DialogoSubirArchivo: {
        Et_TituloPrincipal: 'Subir Archivo',
        Et_NombreArchivo: 'Nombre archivo'
    },
    PaginacionTabla: {
        Et_FilasPagina: 'Filas por página:',
        Et_Elementos: '{0} - {1} de {2}',
    }
};