export const EtiquetasGenerales_EN = {
    General: {
        //---------------------ENCABEZADOS------------------------------
        Et_TituloEliminaRegistro: 'Delete Record',
        Et_TituloEliminaRegistros: 'Delete Records',
        Et_TituloCriterioBusqueda: 'Search criteria',
        Et_TituloConfirmaregistro: 'Confirmation',
        Et_TituloDialogoMensaje: 'Message',
        //---------------------Confirmaciones---------------------------
        TextoEliminarRegistro: 'Do you want to delete this record?? ',
        //---------------------BOTONES----------------------------------
        Et_tbnInsertar: 'Create',
        Et_tbnEditar: 'Edit',
        Et_tbnVisualizar: 'Visualize results',
        Et_tbnGuardar: 'Save',
        Et_tbnAceptar: 'Accept',
        Et_tbnCancelar: 'Cancel',
        Et_tbnEliminar: 'Remove',
        Et_tbnPublicar: 'Publish',
        Et_tbnNoPublicar: 'Not Publish',
        Et_tbnFavorito: 'Bookmark',
        Et_tbnPrincipal: 'Principal',
        Et_tbnLimpiar: 'Clear',
        Et_tbnSi: 'Yes',
        Et_tbnNo: 'No',
        Et_tbnAtras: 'Back',
        Et_tbnSiguiente: 'Next',
        Et_tbnBusqueda: 'Search',
        Et_tbnCerrarSesion: 'Logout',
        Et_tbnSubir: 'Up',
        Et_tbnBajar: 'Down',
        Et_tbnCerrar: 'Close',
        Et_tbnEliminarRegistro: "Yes, delete the record",
        Et_tbnMantenerRegistro: "No, keep the record",
        Et_tbnAgregar: 'Add',
        Et_tbnAgregarC: 'Add content',
        Et_tbnAgregarE: 'Create survey',
        //---------------------TABLAS-----------------------------------
        Et_tblAcciones: 'Actions',
        Et_tblDetalles: 'Details',
        Et_tblTableEmty: "No available data",
        Et_tblItems: 'Rows per page: ',
        Et_tblItemsDescription: "Visible rows {0} to {1} out of a total {2}.",
        //---------------------TEXTOS--------------------------------
        Et_tblSiTildado: 'Yes',
        Et_lblEs: 'Spanish',
        Et_lblEn: 'English',
        Et_lblAllElemnts: 'All',
        Et_tblNombre: 'Name',
        Et_tblCode: 'Code',
        Et_tblDescripcion: 'Description',
        Et_tblEstado: 'Activation',
        Et_tblActivo: 'Active',
        Et_tblInactivo: 'Inactive',
        Et_Select: 'Select',
        Et_Seleccionar: 'Select',
        Et_NoAplica: 'Does not apply',
        Et_tblCusIde: 'ID',
        Et_tblCusOtherIdeShort: 'CIF',
        Et_tblCusOtherIde: 'CIF number',
        Et_tblObservation: 'Observations',
        Et_tblClasificacion: 'Classification',
        Et_tblCategoria: 'Category',
        Et_tblTipo: 'Type',
        Et_tblTipoRequisito: 'Required',
        Et_tblTipoOpcional: 'Optional',
        Et_tblBloque: 'Block',
        Et_tblRequisitos: 'Requirements',
        Et_tblFormatoArchivosPermitidos: 'File formats',
        Et_Requisito: 'Requirement',
        Et_tblRequisitoConAdjunto: 'The requirement requires attaching a file.',
        Et_tblAdminFormatoAdjunto: 'Manage allowed formats',
        Et_tblAdjunto: 'Attached file',
        Et_tblSinOpciones: 'No options',
        Et_tblDatosGenerales: 'General information',
        Et_tblPrograma: 'Program',
        Et_tblProgramas: 'Programs',
        Et_tblTipoPeriodo: 'Period Type',
        Et_tblPeriodo: 'Period',
        Et_tblAnno: 'Year',
        Et_tblSede: 'Campus',
        Et_tblSedes: 'Campus',
        Et_tblFechaAprobacion: 'Approval date',
        Et_tblEstudiante: 'Student',
        Et_tblAprobacion: 'Approval',
        Et_tblArchivo: 'File',
        Et_tblCompania: 'Company',
        Et_tblComentarios: 'Comments',
        Et_tvlAula: 'Classroom',
        Et_tvlAulas: 'Classrooms',
        Et_tvlRecursos: 'Resources',
        Et_tvlEdificio: 'Building',
        Et_tvlPiso: 'Floor',
        Et_tvlTipoAula: 'Classroom Type',
        Et_tvlCapacidad: 'Space available',
        Et_tvlDireccion: 'Address',
        Et_tvlAulaDiscapaitados: 'Handicapped accessible',
        Et_tvlCantidad: 'Quantity',
        Et_tblAprobado: 'Approved',
        Et_tblPendiente: 'Pending',
        Et_tvlJornada: 'Working day',
        Et_tvHoraIncio: 'Start Time',
        Et_tvHoraFinal: 'End Time',
        Et_tvDiasSemana: 'Week days',
        Et_tvLunes: 'Monday',
        Et_tvMartes: 'Tuesday',
        Et_tvMiercoles: 'Wednesday',
        Et_tvJueves: 'Thursday',
        Et_tvViernes: 'Friday',
        Et_tvSabado: 'Saturday',
        Et_tvDomingo: 'Sunday',
        Et_tvListaRecursos: 'Resource list',
        Et_tblInfoRegistrosActivos: '*Only active records will be displayed.',
        Et_FiltroDscRecursos: 'Resource description',
        Et_FiltroDscSede: 'Campus description',
        Et_FiltroDscCursos: 'Couse description',
        Et_FiltroDscFormatos: 'Format description',
        Et_tblGrupo: 'Group',
        Et_tblSubGrupo: 'Subgroup',
        Et_tblPublicado: 'Published',
        Et_tblNoPublicado: 'Unpublished',
        Et_tblCupo: 'Availability:',
        Et_tblIniciaT: 'Start: ',
        Et_tblFinalizaT: 'Ends: ',
        Et_Profesor: 'Instructor',
        Et_Dia: 'Day',
        Et_Horario: 'Schedule',
        Et_tblDetalleFechas: 'Detail Dates',
        Et_tblPeriodoAcademico: 'Academic period',
        Et_tblInscripciones: 'Registrations',
        Et_tblInicioPeriodo: 'Start period',
        Et_tblFinPeriodo: 'End period',
        Et_tblUsuario: 'User',
        Et_tblCliente: 'Customer',
        Et_tblAccion: 'Action',
        Et_tblFechaDesde: 'Date from',
        Et_tblFechaHasta: 'Date to',
        Et_tblGeneral: 'General',
        Et_tblIntensidadHoraria: 'Hourly Intensity',
        Et_ValidaCampoRequerido: 'The {0} field is required.',
    },
    Reportes: {
        Et_TituloPrincipal: 'Reports',
        Et_LblExportaPdf: 'Pdf',
        Et_LblExportaXls: 'Xls',
        Et_LblExportaDoc: 'Doc'
    },
    Login: {
        Et_btnAcceso: 'Access',
        Et_TituloPrincipal: 'Login User',
        Et_txtUsuario: 'Enter your User',
        Et_txtPassword: 'Enter your password'
    },
    HomeModulo: {
        Et_Titulo: 'Explore in the different submodules',
        Et_Parrafo1: 'In the left panel you can find the content you are looking for, try with',
        Et_Parrafo2: 'Favorites or Menu'
    },
    NotFound: {
        Et_btnAccion: 'Back to Home'
    },
    IdiomaModal: {
        Et_TituloPrincipal: 'Select your Language'
    },
    MenuDerecha: {
        Et_btnSalir: 'Log out',
    },
    MenuIzquierda: {
        Et_LblHeader: 'Academic Module',
        Et_LblFavoritos: 'Favorites',
        Et_LblSubmodulos: 'Menu'
    },
    IdleTimeOutModal: {
        Et_txtFinSesionTitulo: 'Your Session has Expired.',
        Et_txtFinSeguir: 'Would you like to continue browsing?'
    },
    CargandoModal: {
        Et_Procesando: "Processing, please wait.",
        Et_Cargando: "Loading, please wait."
    },
    ToolbarButtons: {
        Et_BtnEnviar: 'Send',
        Et_BtnAjustes: 'Settings',
        Et_BtnImprimir: 'Print'
    },
    DialogoSubirImagen: {
        Et_TituloPrincipal: 'Upload Image',
        Et_FotoPerfil: 'Profile picture',
        Et_BtnSubir: 'Upload Photo',
        Et_BtnCamara: 'Take Photo'
    },
    DialogoSubirArchivo: {
        Et_TituloPrincipal: 'Upload File',
        Et_NombreArchivo: 'File name'
    },
    PaginacionTabla: {
        Et_FilasPagina: 'Rows per page:',
        Et_Elementos: '{0} - {1} of {2}',
    }
};